-- MySQL Script generated by MySQL Workbench
-- Mon Oct 10 21:52:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dentistry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dentistry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dentistry` DEFAULT CHARACTER SET utf8 ;
USE `dentistry` ;

-- -----------------------------------------------------
-- Table `dentistry`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentistry`.`clients` (
  `id_clients` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_clients`),
  UNIQUE INDEX `id_clients_UNIQUE` (`id_clients` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentistry`.`service_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentistry`.`service_categories` (
  `id_service_categoty` INT NOT NULL AUTO_INCREMENT,
  `service_category` VARCHAR(45) NULL,
  PRIMARY KEY (`id_service_categoty`),
  UNIQUE INDEX `id_services_UNIQUE` (`id_service_categoty` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentistry`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentistry`.`appointments` (
  `id_appointments` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NULL,
  `phone_number` VARCHAR(45) NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `service_category_id` INT NULL,
  `message` TEXT(250) NULL,
  PRIMARY KEY (`id_appointments`),
  UNIQUE INDEX `id_appointments_UNIQUE` (`id_appointments` ASC) VISIBLE,
  INDEX `FK_first_name_idx` (`client_id` ASC) VISIBLE,
  INDEX `FK_service_category_idx` (`service_category_id` ASC) VISIBLE,
  CONSTRAINT `FK_first_name`
    FOREIGN KEY (`client_id`)
    REFERENCES `dentistry`.`clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_service_category`
    FOREIGN KEY (`service_category_id`)
    REFERENCES `dentistry`.`service_categories` (`id_service_categoty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentistry`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentistry`.`service` (
  `id_service` INT NOT NULL,
  `service_caterogy_id` INT NULL,
  `service` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`id_service`),
  INDEX `FK_service_categoty_idx` (`service_caterogy_id` ASC) VISIBLE,
  CONSTRAINT `FK_service_categoty`
    FOREIGN KEY (`service_caterogy_id`)
    REFERENCES `dentistry`.`service_categories` (`id_service_categoty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentistry`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentistry`.`personal` (
  `id_personal` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `work_experience` VARCHAR(45) NULL,
  `appointment_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id_personal`),
  UNIQUE INDEX `id_personal_UNIQUE` (`id_personal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentistry`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentistry`.`comments` (
  `id_comments` INT NOT NULL,
  `client_id` INT NULL,
  `service_category_id` INT NULL,
  `dentist_id` INT NULL,
  `comment` TEXT(300) NULL,
  PRIMARY KEY (`id_comments`),
  INDEX `FK_client_id_idx` (`client_id` ASC) VISIBLE,
  INDEX `FK_services_category_idx` (`service_category_id` ASC) VISIBLE,
  INDEX `FK_dentist_id_idx` (`dentist_id` ASC) VISIBLE,
  CONSTRAINT `FK_client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `dentistry`.`clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_services_category`
    FOREIGN KEY (`service_category_id`)
    REFERENCES `dentistry`.`service_categories` (`id_service_categoty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_dentist_id`
    FOREIGN KEY (`dentist_id`)
    REFERENCES `dentistry`.`personal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
